# Use an official Node.js image as the base image
FROM node:22.4.1

# Expose the port the app runs on (optional, if you plan to expose a port in the future)
EXPOSE 3000

# Command to run the Node.js REPL
CMD ["node"]
